import { A } from './motor.mjs'
const { topo, centro, passo, aba, junta } = A

export const operador = [
  { t: 'Olá! Este é o guia do operador de portão do Credenciei. Vou mostrar, passo a passo, como usar o sistema no dia do evento.', a: topo },
  { t: 'Primeiro, o seu acesso. Só o administrador do evento, ou o suporte do Credenciei, criam o acesso de operador de portão. Você não cria o seu, e o supervisor também não cria.', a: centro('#acesso .callout') },
  { t: 'Quando o acesso é criado, chega uma mensagem no seu Uatsápi, com um link só seu.', a: junta(centro('#acesso .tour'), passo('#acesso .tour', 0)) },
  { t: 'Abra o link e crie a sua senha. O seu login é o seu cê-pê-éfe.', a: passo('#acesso .tour', 1) },
  { t: 'Depois é só entrar com o cê-pê-éfe e a senha.', a: passo('#acesso .tour', 2) },
  { t: 'Na tela de boas-vindas, escolha o evento. Os que estão acontecendo hoje aparecem primeiro.', a: passo('#acesso .tour', 3) },
  { t: 'Para trocar de evento, toque no botão do evento, lá em cima, ao lado do Suporte. Para trocar de perfil, toque na sua foto, e escolha Operador de portão.', a: centro('#trocar .dia') },
  { t: 'Agora, o escâner. Toque em Escâner. Ele só abre no dia do evento.', a: junta(centro('#scanner .tour'), passo('#scanner .tour', 0)) },
  { t: 'Confira o evento, e escolha entrada ou saída. Quem saiu e está voltando também usa entrada.', a: passo('#scanner .tour', 1) },
  { t: 'Aponte a câmera para o Quê Érre Côde da credencial. O leitor reconhece sozinho.', a: passo('#scanner .tour', 2) },
  { t: 'A tela mostra quem é a pessoa, e o que vai ser registrado. Toque em salvar. Se não for ela, toque em cancelar, e nada é gravado.', a: passo('#scanner .tour', 3) },
  { t: 'Pronto! Se a tela ficar verde, o acesso está liberado.', a: passo('#scanner .tour', 4) },
  { t: 'Preste atenção nas cores. Verde, pode entrar. Azul, é saída. Amarelo, já foi validado. Laranja, é de outra área. Vermelho, não libere.', a: centro('#scanner .res-grid') },
  { t: 'Em evento com subeventos, o escâner pergunta: qual área você vai atuar?', a: junta(centro('#areas .tour'), passo('#areas .tour', 0)) },
  { t: 'Marque uma ou mais áreas, e toque em confirmar.', a: passo('#areas .tour', 1) },
  { t: 'A área escolhida fica no topo. Para trocar, toque em alterar.', a: passo('#areas .tour', 2) },
  { t: 'Se a pessoa chegou sem o Quê Érre Côde, use o Registrar ponto.', a: junta(centro('#registro .tour'), passo('#registro .tour', 0)) },
  { t: 'Procure pelo nome, ou pelo cê-pê-éfe.', a: passo('#registro .tour', 1) },
  { t: 'Confira a ficha, e escolha a batida.', a: passo('#registro .tour', 2) },
  { t: 'Tire a foto do rosto da pessoa. Sem a foto, o sistema não deixa registrar.', a: passo('#registro .tour', 3) },
  { t: 'Toque em registrar. Pronto!', a: passo('#registro .tour', 4) },
  { t: 'Muito importante. Se a pessoa disser que não recebeu o Quê Érre Côde, mande ela procurar o supervisor dela.', a: centro('#semqr .callout') },
  { t: 'O supervisor passa o link de cadastro, e aprova o pedido. Só depois disso o Quê Érre Côde chega no Uatsápi da pessoa.', a: centro('#semqr .flow') },
  { t: 'Você não gera o Quê Érre Côde, e não aprova ninguém. Seu papel é orientar a pessoa.', a: centro('#semqr .cases') },
  { t: 'Lembre-se: o escâner só aparece no dia do evento. Fora do dia, ele fica desligado.', a: centro('#dia .callout') },
  { t: 'Pronto! Se tiver qualquer dúvida, toque no botão verde Suporte, lá em cima. Boa operação!', a: topo },
]

export const supervisor = [
  { t: 'Olá! Este é o guia do supervisor do Credenciei. Vou mostrar como montar a sua equipe, e como acompanhar o evento.', a: topo },
  { t: 'Primeiro, o acesso. Quando você é cadastrado como supervisor, chega uma mensagem no seu Uatsápi, com um link só seu.', a: junta(centro('#acesso .tour'), passo('#acesso .tour', 0)) },
  { t: 'Abra o link e crie a sua senha. O seu login é o seu cê-pê-éfe.', a: passo('#acesso .tour', 1) },
  { t: 'Entre com o cê-pê-éfe e a senha. Se esquecer a senha, toque em esqueci a senha, e um novo link chega no seu Uatsápi.', a: passo('#acesso .tour', 2) },
  { t: 'Depois, escolha o evento e o setor. Com mais de um evento, troque pelo botão do evento, lá em cima.', a: passo('#acesso .tour', 3) },
  { t: 'Para montar a equipe, são dois jeitos: por link, ou por planilha. Você pode usar os dois no mesmo setor.', a: centro('#equipe .compare') },
  { t: 'Por link. No painel do seu setor, toque em Link cadastro. O link já fica copiado.', a: junta(centro('#link .tour'), passo('#link .tour', 0)) },
  { t: 'Cole o link no grupo do Uatsápi da equipe. Cada pessoa faz o próprio cadastro.', a: passo('#link .tour', 1) },
  { t: 'Cada pessoa preenche em menos de dois minutos: nome, cê-pê-éfe, Uatsápi e cidade.', a: passo('#link .tour', 2) },
  { t: 'O pedido chega até você, aguardando aprovação. Um número aparece no menu, para você saber que tem gente esperando.', a: passo('#link .tour', 3) },
  { t: 'Por planilha. Baixe o modelo. Ele já vem com as colunas certas.', a: junta(centro('#planilha .tour'), passo('#planilha .tour', 0)) },
  { t: 'Preencha uma linha por pessoa. Nome e cê-pê-éfe são o que mais importa.', a: passo('#planilha .tour', 1) },
  { t: 'Depois, importe o arquivo da planilha.', a: passo('#planilha .tour', 2) },
  { t: 'Confira o resultado. O sistema mostra quem entrou, e quem ficou de fora, com o motivo. Quem entra por planilha já está aprovado.', a: passo('#planilha .tour', 3) },
  { t: 'Quem entra por link espera o seu sim. Em Aguardando aprovação, toque em aprovar.', a: junta(centro('#aprovar .tour'), passo('#aprovar .tour', 0)) },
  { t: 'Ao aprovar, a pessoa recebe o Quê Érre Côde no Uatsápi. É com ele que ela entra no evento.', a: passo('#aprovar .tour', 1) },
  { t: 'Ou negue, e escreva o motivo, se quiser.', a: passo('#aprovar .tour', 2) },
  { t: 'Passados cinco minutos, a pessoa pode refazer o pedido pelo mesmo link, e ele volta para a sua fila.', a: passo('#aprovar .tour', 3) },
  { t: 'No fim do evento, avalie a equipe. Abra Avaliar equipe.', a: junta(centro('#depoimentos .tour'), passo('#depoimentos .tour', 0)) },
  { t: 'Dê de uma a cinco estrelas para cada pessoa.', a: passo('#depoimentos .tour', 1) },
  { t: 'E, se quiser, escreva um depoimento. É opcional.', a: passo('#depoimentos .tour', 2) },
  { t: 'Pronto! Se tiver qualquer dúvida, toque no botão verde Suporte, lá em cima. Bom evento!', a: topo },
]

export const encarregado = [
  { t: 'Olá! Este é o guia do Encarregado do Credenciei. Você consulta a equipe do seu setor.', a: topo },
  { t: 'O supervisor do seu setor cria o seu acesso. Você precisa já estar na equipe.', a: centro('#acesso .callout') },
  { t: 'Chega uma mensagem no seu Uatsápi, com um link.', a: junta(centro('#acesso .tour'), passo('#acesso .tour', 0)) },
  { t: 'Crie a sua senha. O seu login é o seu cê-pê-éfe.', a: passo('#acesso .tour', 1) },
  { t: 'Entre com o cê-pê-éfe e a senha.', a: passo('#acesso .tour', 2) },
  { t: 'E veja o seu setor.', a: passo('#acesso .tour', 3) },
  { t: 'Você só consulta. Pode ver a equipe, ver quem chegou e quem falta, e abrir os dados e o histórico de cada pessoa. Não pode registrar ponto, aprovar ou editar, nem ver outros setores.', a: centro('#voce .compare') },
  { t: 'Com mais de um evento, ou mais de um setor, escolha o evento, depois o setor. E troque quando quiser, pelo botão do evento, lá em cima.', a: centro('#varios .flow') },
  { t: 'Estas são as telas de verdade. Primeiro, a equipe, com os números do dia.', a: junta(centro('#telas .browser'), aba('t1')) },
  { t: 'Depois, os dados da pessoa. É somente leitura.', a: aba('t2') },
  { t: 'E o histórico, dia a dia.', a: aba('t3') },
  { t: 'Pronto! Se tiver qualquer dúvida, toque no botão verde Suporte, lá em cima.', a: topo },
]
