/**
 * Os rótulos da auditoria — num arquivo só deles, sem nenhum import.
 *
 * Moravam em lib/suporte.ts, que importa o cliente de serviço do Supabase.
 * São texto puro e a tela de auditoria precisa deles no NAVEGADOR (o select
 * de ação, o nome do arquivo exportado) — e aí o bundle do cliente puxava
 * junto a chave de serviço. Separados, cada lado importa só o que é.
 */

/** Rótulos das ações gravadas em `alteracoes_cadastro` — usados na tela de auditoria. */
export const ACAO_LABELS: Record<string, string> = {
  CADASTRO_FUNCIONARIO: 'Cadastro',
  ALTERACAO_CPF: 'Correção de CPF',
  ALTERACAO_NOME: 'Correção de nome',
  ALTERACAO_TELEFONE: 'Correção de telefone',
  ALTERACAO_SETOR: 'Mudança de fornecedor',
  ATIVACAO_FUNCIONARIO: 'Ativação',
  DESATIVACAO_FUNCIONARIO: 'Desativação',
  CADASTRO_EMERGENCIAL: 'Cadastro emergencial',
  REGISTRO_ENTRADA_ASSISTIDA: 'Entrada assistida',
  REGISTRO_SAIDA_ASSISTIDA: 'Saída assistida',
  CORRECAO_PONTO: 'Correção de ponto',
  DESCREDENCIAMENTO: 'Descredenciamento',
  EXCLUSAO_FUNCIONARIO: 'Funcionário excluído',
  BLOQUEIO_CPF: 'CPF bloqueado',
  DESBLOQUEIO_CPF: 'CPF liberado',
  EXCLUSAO_PONTO: 'Batida apagada',
  RESET_SENHA: 'Redefinição de senha',
  ALTERACAO_SUPERVISOR: 'Alteração de supervisor',
  ALTERACAO_OPERADOR: 'Alteração de operador de portão',
  ALTERACAO_PERMISSAO: 'Permissão alterada',
  REABERTURA_TURNO: 'Voltou a trabalhar (turno reaberto)',
  ENTRADA_VEICULO_LIBERADA: 'Entrada de veículo liberada',
  APROVACAO_CREDENCIAMENTO: 'Credenciamento aprovado',
  NEGACAO_CREDENCIAMENTO: 'Credenciamento negado',
  NOVO_PEDIDO_CREDENCIAMENTO: 'Novo pedido de credenciamento (após negativa)',
  APROVACAO_ESCALA: 'Dias de trabalho aprovados',
  AJUSTE_ESCALA: 'Dias de trabalho ajustados',
  MESCLA_SUBEVENTO: 'Subeventos mesclados',
  EDICAO_BASE_FUNCIONARIO: 'Dados da pessoa editados na base',
  DEPOIMENTO_COLABORADOR: 'Depoimento sobre colaborador',
  AVALIACAO_COLABORADOR: 'Colaborador avaliado (estrelas)',
  TROCA_DE_PERFIL: 'Troca de perfil',
  CONCESSAO_ENCARREGADO: 'Encarregado designado',
  REMOCAO_ENCARREGADO: 'Encarregado removido',
  ALTERACAO_FUNCIONALIDADE: 'Funcionalidade alterada',
  // ── Cobertura completa (08/10/2026: "tudo que acontece no sistema precisa estar na auditoria") ──
  ORGANIZACAO_CRIADA: 'Organização criada',
  ORGANIZACAO_EDITADA: 'Organização editada',
  ORGANIZACAO_SITUACAO: 'Organização ativada/suspensa',
  ORGANIZACAO_EXCLUIDA: 'Organização excluída',
  TOTEM_CRIADO: 'Totem criado',
  TOTEM_EDITADO: 'Totem editado',
  SUPORTE_CRIADO: 'Acesso de suporte criado',
  SUPORTE_EDITADO: 'Acesso de suporte editado',
  SUPORTE_REVOGADO: 'Acesso de suporte revogado',
  LINK_DE_ACESSO_GERADO: 'Link de acesso gerado',
  RECUPERACAO_SENHA_SOLICITADA: 'Recuperação de senha pedida',
  SUPERVISOR_EDITADO: 'Supervisor editado',
  USUARIO_EXCLUIDO: 'Usuário excluído',
  EVENTO_CRIADO: 'Evento criado',
  EVENTO_EDITADO: 'Evento editado',
  EVENTO_EXCLUIDO: 'Evento excluído',
  EVENTO_ORGANIZACAO_ALTERADA: 'Evento mudou de organização',
  SETOR_CRIADO: 'Fornecedor criado',
  SETOR_EDITADO: 'Fornecedor editado',
  SETOR_EXCLUIDO: 'Fornecedor excluído',
  COLABORADOR_ATRIBUIDO: 'Pessoa da base colocada no evento',
  VALOR_A_RECEBER_ALTERADO: 'Valor a receber alterado',
  PAGAMENTO_ALTERADO: 'Pagamento marcado/desmarcado',
  DIAS_DO_EVENTO_ALTERADOS: 'Dias de trabalho do evento alterados',
  RECREDENCIAMENTO: 'Voltou para a equipe',
  BIOMETRIA_CONSENTIMENTO: 'Consentimento de biometria',
  BIOMETRIA_CADASTRADA: 'Biometria cadastrada',
  PORTARIA_ALTERADA: 'Cadastro pela portaria ligado/desligado',
  PORTARIA_TOKEN_TROCADO: 'QR da portaria trocado',
  CADASTRO_POR_LINK_ALTERADO: 'Cadastro por link aberto/suspenso',
  LINK_DO_SETOR_ALTERADO: 'Link do fornecedor ligado/desligado',
  CONFIGURACAO_MEIO_ALTERADA: 'Batida do meio configurada',
  LOCAL_DO_EVENTO_ALTERADO: 'Local do evento alterado',
  AVISO_CRIADO: 'Aviso criado',
  AVISO_EDITADO: 'Aviso editado',
  AVISO_SITUACAO: 'Aviso ativado/desativado',
  AVISO_EXCLUIDO: 'Aviso excluído',
  VEICULO_CADASTRADO: 'Veículo cadastrado',
  VEICULO_FOTO_ALTERADA: 'Foto do veículo alterada',
  VEICULO_STATUS_ALTERADO: 'Situação do veículo alterada',
  VEICULO_LINK_ALTERADO: 'Link de veículos alterado',
  VEICULO_EXCLUIDO: 'Veículo excluído',
  ESTRUTURA_IMPORTADA: 'Estrutura importada por planilha',
  SUBEVENTO_CRIADO: 'Subevento criado',
  SUBEVENTO_EDITADO: 'Subevento editado',
  SUBEVENTO_EXCLUIDO: 'Subevento excluído',
  PEDIDO_SETOR_ENVIADO: 'Pedido de setor recebido',
  PEDIDO_SETOR_EDITADO: 'Pedido de setor editado',
  LINK_PEDIDO_SETOR_TROCADO: 'Endereço do pedido de setor trocado',
  WHATSAPP_DISPARO: 'Disparo de WhatsApp',
  WHATSAPP_FLUXOS_ALTERADOS: 'Respostas automáticas do WhatsApp alteradas',
  GASTO_CRIADO: 'Gasto lançado',
  GASTO_EDITADO: 'Gasto editado',
  GASTO_EXCLUIDO: 'Gasto excluído',
  BACKLOG_CRIADO: 'Backlog: item criado',
  BACKLOG_EDITADO: 'Backlog: item editado',
  BACKLOG_MOVIDO: 'Backlog: item movido',
  BACKLOG_COMENTARIO: 'Backlog: comentário',
  BACKLOG_CONVERTIDO_CLIENTE: 'Backlog: virou cliente',
  BACKLOG_EXCLUIDO: 'Backlog: item excluído',
  BACKLOG_ANEXO: 'Backlog: anexo incluído/removido',
  FATURAMENTO_ALTERADO: 'Faturamento alterado',
  CUSTO_CRIADO: 'Custo lançado',
  CUSTO_EDITADO: 'Custo editado',
  CUSTO_EXCLUIDO: 'Custo excluído',
  ORCAMENTO_CRIADO: 'Orçamento criado',
  ORCAMENTO_EDITADO: 'Orçamento editado',
  ORCAMENTO_EXCLUIDO: 'Orçamento excluído',
  ORCAMENTO_DUPLICADO: 'Orçamento duplicado',
  MONITORAMENTO_ALTERADO: 'Monitoramento de serviço alterado',
  INCIDENTE_MARCADO: 'Incidente marcado',
  RESTAURACAO_FUNCIONARIO: 'Funcionário restaurado da lixeira',
  RESTAURACAO_PONTO: 'Batida restaurada',
  ALTERACAO_LINK_PEDIDO_SETOR: 'Link de pedido de setor alterado',
  APROVACAO_PEDIDO_SETOR: 'Pedido de setor aprovado',
  NEGACAO_PEDIDO_SETOR: 'Pedido de setor negado',
  PEDIDO_AMPLIACAO: 'Pedido de mais colaboradores',
  APROVACAO_AMPLIACAO: 'Mais colaboradores aprovado',
  NEGACAO_AMPLIACAO: 'Mais colaboradores negado',
  AUTOATENDIMENTO_ATIVADO: 'Autoatendimento ativado (operador foi embora)',
  AUTOATENDIMENTO_DESATIVADO: 'Autoatendimento desativado (operador chegou)',
  TRAVA_POR_DIA_ALTERADA: 'Limite por dia alterado',
  TENTATIVA_FORA_DO_LOCAL: 'Tentou bater o ponto fora do local do evento',
  AUTOATENDIMENTO_CONFIGURADO: 'Autoatendimento configurado (horário e dias)',
  REGISTRO_AUTOATENDIMENTO: 'Ponto batido pelo colaborador (fora do horário da portaria)',
}

/** Motivos padrão pra alteração sensível — a UI oferece estes + "Outro" com texto livre. */
export const MOTIVOS_PADRAO = [
  'CPF incorreto',
  'Nome incorreto',
  'Telefone incorreto',
  'Fornecedor incorreto',
  'Função incorreta',
  'Cadastro emergencial',
  'Correção solicitada pelo responsável',
  'Problema operacional',
] as const
